version: '3.7'
services:
  app:
    build: ./docker
    container_name: rest-api-tutorial
    ports:
      - 8081:8080
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - flyway
  db:
    image: postgres:12.11
    container_name: rest-api-db
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=dev
  flyway:
    image: flyway/flyway
    container_name: rest-api-migration
    environment:
      - FLYWAY_URL=${SPRING_DATASOURCE_URL}
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
    command: -connectRetries=60 migrate info
    volumes:
      - ./docker/flyway/sql:/flyway/sql
    depends_on:
      - db