version: "3.7"
services:
  swagger_editor:
    image: swaggerapi/swagger-editor
    container_name: 'swagger-api'
    ports:
      - "8887:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui:v5.1.0
    container_name: 'swagger-ui'
    ports:
      - "8888:8080"
    volumes:
      - "./docs:/usr/share/nginx/html/docs"
    environment:
      - URL=./docs/openapi.yml

  swagger-merger:
    build: ./docker/swagger/swagger-merger/
    command: watch 'swagger-merger -i /docs/index.yml -o /docs/openapi.yml' /docs/
    volumes:
      - "./docs:/docs"