version: '3.7'
services:
  app:
    build: ./docker
    container_name: rest-api-tutorial
    ports:
      - 8081:8080
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dev
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - flyway
  db:
    image: postgres:12.11
    container_name: rest-api-db
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dev
  flyway:
    image: flyway/flyway
    container_name: rest-api-migration
    command: -connectRetries=60 migrate info
    volumes:
      - ./docker/flyway/conf:/flyway/conf
      - ./docker/flyway/sql:/flyway/sql
    depends_on:
      - db