openapi: 3.0.3
info:
  title: rest-api-tutorial
  version: 0.0.1
  description: rest-api-tutorial
servers:
  - url: http://localhost:8080
tags:
  - name: member
    description: 会員情報
paths:
  /v1/members:
    get:
      tags:
        - member
      operationId: featchMembers
      description: 会員を全件取得します
      responses:
        '200':
          description: 成功時
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    firstName:
                      type: string
                    lastName:
                      type: string
              examples:
                test:
                  value: '[{id: 1, firstName: "hoge", lastName: "piyo"}]'
  /v1/members/{memberId}:
    get:
      tags:
        - member
      operationId: findMember
      description: 指定されたmemberIdの情報を取得します
      parameters:
        - name: memberId
          in: path
          description: 取得したいmemberId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 成功時
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  firstName:
                    type: string
                  lastName:
                    type: string
        '404':
          description: 指定されたmemberIdに紐づいた情報が存在しませんでした

