openapi: 3.0.3
info:
  title: rest-api-tutorial
  version: 0.0.1
  description: rest-api-tutorial
servers:
  - url: http://localhost:8080
tags:
  - name: member
    description: 会員情報
paths:
  /v1/members:
    get:
      tags:
        - member
      operationId: featchMembers
      description: 会員を全件取得します
      responses:
        '200':
          description: 成功時
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  description: 会員
                  properties:
                    id:
                      type: integer
                      example: 1
                    firstName:
                      type: string
                      example: hoge
                    lastName:
                      type: string
                      example: fuga
  /v1/members/{memberId}:
    get:
      tags:
        - member
      operationId: findMember
      description: 指定されたmemberIdの情報を取得します
      parameters:
        - name: memberId
          in: path
          description: 取得したいmemberId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 成功時
          content:
            application/json:
              schema:
                type: object
                description: 会員
                properties:
                  id:
                    type: integer
                    example: 1
                  firstName:
                    type: string
                    example: hoge
                  lastName:
                    type: string
                    example: fuga
        '404':
          description: 指定されたmemberIdに紐づいた情報が存在しませんでした
components:
  schemas:
    member:
      type: object
      description: 会員
      properties:
        id:
          type: integer
          example: 1
        firstName:
          type: string
          example: hoge
        lastName:
          type: string
          example: fuga
